### ISSUE TITLE
STA9750 Chloe384 MiniProject #00

### ISSUE THREAD

**Issue by Chloe384** [Chloe384/STA9750-2024-FALL#1]
Hi @michaelweylandt!

I've created my STA9750 website - check it out!

https://chloe384.github.io/STA9750-2024-FALL

**Comment by michaelweylandt** [comment]
Thanks @Chloe384 !

Peer Feedback:

- @Slyastrologer
- @greazyz
- @jasonamey

Please a look at the website associated with this GitHub repo
and provide some peer feedback to @Chloe384.

Website URL should be: https://Chloe384.github.io/STA9750-2024-FALL/

If that link doesn't work, please check out the GitHub profile for @Chloe384 and
see if you can help them get it working.

At a minimum, please note:

1. Something you like about the submission.
2. A suggestion on how to improve it.

Feel free to link to other repos, the course documentation, or other useful
examples.

This submission is ungraded, so there's you don't need to provide
a numerical score.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by ghost** [comment]
Hi @Chloe384,

I like that you included your prior background with regard to coding in your submission; it really helps to contextualize your skillset coming into the class. As a suggestion for next time, consider including some interactive or visual elements (such as links or photos) to add depth to your site!

**Comment by greazyz** [comment]
Hi Chloe, this is also my first course focused on coding! I like your use
of paragraphs to separate each block of text. You can add more markdowns,
such as emphasis, to highlight some of your facts!
