### ISSUE TITLE
Can't Open Mini Project 01 Link

### ISSUE THREAD

**Issue by Chloe384** [Chloe384/STA9750-2024-FALL#4]
Hi @Haina0,

This is Chloe. I am having trouble opening the following link to mini project #01. Can you check the URL link and update me with your new link? Thanks!

https://haina0.github.io/STA9750-2024-FALL/mp01.html

**Comment by Haina0** [comment]
Hi @Chloe384 

Thank you for letting me know; try this link. 
https://github.com/Haina0/docs-mp02.html
